### ISSUE TITLE
Pretrained configuration loading error

### ISSUE THREAD

**Issue by relf** [femshima/segmentation-models-burn#2]
Using the preset configuration :
```
let encoder_conf = EfficientNetConfigPreset::new(EfficientNetKind::EfficientnetB0)
        .with_weight(Some(EfficientNetWeightKind::Normal));
```
I get the following error:
```
efficientnet-b0-355c32eb.pth
    ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬ 20.40 MiB/20.40 MiB (0.0s)thread 'main' panicked at /tmp_user/juno/rlafage/workspace/segmentation-models-burn/src/encoder/efficientnet/presets.rs:62:46:
called `Result::unwrap()` on an `Err` value: DeserializeError("Candle pickle error: invalid Zip archive: Could not find central directory end")
stack backtrace:
   0: rust_begin_unwind
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/panicking.rs:662:5
   1: core::panicking::panic_fmt
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/panicking.rs:74:14
   2: core::result::unwrap_failed
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/result.rs:1677:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/result.rs:1102:23
   4: <segmentation_models_burn::encoder::efficientnet::presets::EfficientNetConfigPreset as segmentation_models_burn::encoder::EncoderConfig<B>>::init
             at /tmp_user/juno/rlafage/workspace/segmentation-models-burn/src/encoder/efficientnet/presets.rs:62:9
   5: <segmentation_models_burn::model::ModelConfig<EC,DC> as segmentation_models_burn::model::ModelInit<B,EC,DC>>::init
             at /tmp_user/juno/rlafage/workspace/segmentation-models-burn/src/model.rs:198:23
   6: spotcontrail::model::ModelConfig::init
             at ./src/model.rs:69:20
   7: spotcontrail::training::run
             at ./src/training.rs:115:21
   8: spotcontrail::tch_cpu::run
             at ./src/main.rs:73:9
   9: spotcontrail::main
             at ./src/main.rs:91:5
  10: core::ops::function::FnOnce::call_once
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/ops/function.rs:250:5
```

I noticed the [FIXME comment](https://github.com/femshima/segmentation-models-burn/blob/2dc69397fbb2d336b8c388dfda1145da1eb8946a/src/encoder/efficientnet/presets.rs#L149), the link work though the file format does not seem to be the correct one.

**Comment by relf** [comment]
Maybe related to https://github.com/huggingface/candle/issues/1348

**Comment by femshima** [comment]
As you mentioned, it's because candle cannot handle older pytorch version. You can convert it using the following code.

```py
import torch

weights=torch.load("efficientnet-b0-355c32eb.pth")
torch.save(weights, "updated/efficientnet-b0-355c32eb.pth")

weights=torch.load("updated/efficientnet-b0-355c32eb.pth")
w={}
for param_tensor in weights:
    w[param_tensor]=weights[param_tensor].contiguous()
    print(param_tensor, "\t", weights[param_tensor].size(), "\t", weights[param_tensor].stride())
torch.save(w, "updated/efficientnet-b0-355c32eb.pth")
```

**Comment by relf** [comment]
Yep I came up with this same idea and it solves the problem. Thanks!
